steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/nice-theater-386506/gke_sample:v1.0'
      - '.'

  # Tag the Docker image for Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - 'gcr.io/nice-theater-386506/gke_sample:v1.0'
      - 'asia-south2-docker.pkg.dev/nice-theater-386506/gke-pipeline/gke_sample:v1.0'

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south2-docker.pkg.dev/nice-theater-386506/gke-pipeline/gke_sample:v1.0'

  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--filename=deployment.yaml'
      - '--location=us-central1'
      - '--cluster=microservice1'
      - '--namespace=default'
      - '--image=asia-south2-docker.pkg.dev/nice-theater-386506/gke-pipeline/gke_sample:v1.0'

options:
  logging: NONE
