steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gke_sample:$COMMIT_SHA'
      - '.'

  # Tag the Docker image for Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - 'gcr.io/$PROJECT_ID/gke_sample:$COMMIT_SHA'
      - 'LOCATION-docker.pkg.dev/$PROJECT_ID/REPO_NAME/gke_sample:$COMMIT_SHA'

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'LOCATION-docker.pkg.dev/$PROJECT_ID/REPO_NAME/gke_sample:$COMMIT_SHA'

  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--filename=deployment.yaml'
      - '--location=_GKE_CLUSTER_LOCATION'
      - '--cluster=_GKE_CLUSTER_NAME'
      - '--namespace=default'

substitutions:
  _PROJECT_ID: "nice-theater-386506"
  _COMMIT_SHA: "$(git rev-parse --short HEAD)"
  _LOCATION: "asia-south2-docker.pkg.dev"
  _REPO_NAME: "gke-pipeline"
  _GKE_CLUSTER_LOCATION: "us-central1"
  _GKE_CLUSTER_NAME: "microservice1"
